name: Go Sandbox CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ginkgo-hello-test:
    defaults:
      run:
        working-directory: ./ginkgo-hello
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: ginkgo-hello/go.sum
          go-version-file: ginkgo-hello/go.mod

      - run: go version
      - run: go get . -t -v
      - run: go test -v ./...

  greet-build:
    defaults:
      run:
        working-directory: ./greet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: greet/go.sum
          go-version-file: greet/go.mod

      - run: go version
      - run: go get . -v
      - run: go build -v ./...
